export const LOCAL_STORE_INIT = "LOCAL_STORE_INIT";
export const GROUPS_SAVED = "GROUPS_SAVED";
export const CLASSROOMS_SAVED = "CLASSROOMS_SAVED";
export const TEACHERS_SAVED = "TEACHERS_SAVED";

export const SELECT_HANDLER = "SELECT_HANDLER";
export const CALENDAR_SELECT_HANDLER = "CALENDAR_SELECT_HANDLER";

export const GROUPS_NAMES = "GROUPS_NAMES";
export const GROUPS_DELETE_ROW = "GROUPS_DELETE_ROW";
export const GROUPS_ADD_ROW = "GROUPS_ADD_ROW";

export const DISCIPLINES_DELETE_ROW = "DISCIPLINES_DELETE_ROW";
export const DISCIPLINES_ADD_ROW = "DISCIPLINES_ADD_ROW";
export const DISCIPLINES_NAMES = "DISCIPLINES_NAMES";

export const TIMETABLE_NAMES = "TIMETABLE_NAMES";

export const CALENDAR_NAMES = "CALENDAR_NAMES";

export const CLASSROOMS_ALL_DELETE_ROW = "CLASSROOMS_ALL_DELETE_ROW";
export const CLASSROOMS_ALL_ADD_ROW = "CLASSROOMS_ALL_ADD_ROW";
export const CLASSROOMS_ALL_NAMES = "CLASSROOMS_ALL_NAMES";

export const TEACHERS_ALL_DELETE_ROW = "TEACHERS_ALL_DELETE_ROW";
export const TEACHERS_ALL_ADD_ROW = "TEACHERS_ALL_ADD_ROW";
export const TEACHERS_ALL_NAMES = "TEACHERS_ALL_NAMES";

export const UPDATE_TIMETABLE_FROM_FILE = "UPDATE_TIMETABLE_FROM_FILE";
