export const LOCAL_STORE_INIT = "LOCAL_STORE_INIT";
export const GROUPS_SAVED = "GROUPS_SAVED";
export const CLASSROOMS_SAVED = "CLASSROOMS_SAVED";
export const TEACHERS_SAVED = "TEACHERS_SAVED";

export const GROUPS_NAMES = "GROUPS_NAMES";
export const GROUPS_DELETE_ROW = "GROUPS_DELETE_ROW";
export const GROUPS_ADD_ROW = "GROUPS_ADD_ROW";

export const DISCIPLINES_SELECT_HANDLER = "DISCIPLINES_SELECT_HANDLER";
export const DISCIPLINES_DELETE_ROW = "DISCIPLINES_DELETE_ROW";
export const DISCIPLINES_ADD_ROW = "DISCIPLINES_ADD_ROW";
export const DISCIPLINES_NAMES = "DISCIPLINES_NAMES";

export const TIMETABLE_DELETE_ROW = "TIMETABLE_DELETE_ROW";
export const TIMETABLE_NAMES = "TIMETABLE_NAMES";

export const CALENDAR_SELECT_HANDLER = "CALENDAR_SELECT_HANDLER";
export const CALENDAR_DELETE_ROW = "CALENDAR_DELETE_ROW";
export const CALENDAR_NAMES = "CALENDAR_NAMES";

export const CLASSROOMS_ALL_DELETE_ROW = "CLASSROOMS_ALL_DELETE_ROW";
export const CLASSROOMS_ALL_ADD_ROW = "CLASSROOMS_ALL_ADD_ROW";
export const CLASSROOMS_ALL_NAMES = "CLASSROOMS_ALL_NAMES";

export const TEACHERS_ALL_DELETE_ROW = "TEACHERS_ALL_DELETE_ROW";
export const TEACHERS_ALL_ADD_ROW = "TEACHERS_ALL_ADD_ROW";
export const TEACHERS_ALL_NAMES = "TEACHERS_ALL_NAMES";

export const CLASSROOMS_SELECT_HANDLER = "CLASSROOMS_SELECT_HANDLER";
export const TEACHERS_SELECT_HANDLER = "TEACHER_SELECT_HANDLER";
export const DISCIPLINE_SELECT_HANDLER = "DISCIPLINE_SELECT_HANDLER";
