export const LOCAL_STORE_INIT = "LOCAL_STORE_INIT";
export const LOCAL_STORE_CHANGES_INIT = "LOCAL_STORE_CHANGES_INIT";

export const GROUPS_NAMES = "GROUPS_NAMES";
export const GROUPS_DELETE_ROW = "GROUPS_DELETE_ROW";
export const GROUPS_ADD_ROW = "GROUPS_ADD_ROW";
export const GROUPS_SAVED = "GROUPS_SAVED";
export const GROUPS_CHANGES_SAVED = "GROUPS_CHANGES_SAVED";

export const DISCIPLINES_SELECT_HANDLER = "DISCIPLINES_SELECT_HANDLER";
export const DISCIPLINES_DELETE_ROW = "DISCIPLINES_DELETE_ROW";
export const DISCIPLINES_ADD_ROW = "DISCIPLINES_ADD_ROW";
export const DISCIPLINES_NAMES = "DISCIPLINES_NAMES";

export const TIMETABLE_DELETE_ROW = "TIMETABLE_DELETE_ROW";
export const TIMETABLE_ADD_ROW = "TIMETABLE_ADD_ROW";
export const TIMETABLE_ADD_DAY = "TIMETABLE_ADD_DAY";
export const TIMETABLE_NAMES = "TIMETABLE_NAMES";

export const CALENDAR_SELECT_HANDLER = "CALENDAR_SELECT_HANDLER";
export const CALENDAR_DELETE_ROW = "CALENDAR_DELETE_ROW";
export const CALENDAR_ADD_ROW = "CALENDAR_ADD_ROW";
export const CALENDAR_NAMES = "CALENDAR_NAMES";
